---
- hosts: all

  tasks:
    - include_vars: config.yml

    - include: system.yml
    - include: java.yml
    - include: packages.yml
    - include: agora-tools/main.yml
    - include: agora-elections/main.yml
