---
- hosts: all

  tasks:
    - include_vars: config.yml
    #- include: helo.yml

    - include: java.yml
    - include: packages.yml
    - include: users.yml
    - include: commands.yml
    - include: verificatum.yml
