---
- hosts: all

  tasks:
    - include_vars: config.yml

    - include: java.yml
    - include: packages.yml
    - include: users.yml
    - include: commands.yml
    - include: verificatum.yml
    - include: eorchestra.yml
    - include: agora-elections/main.yml
    #- include: authapi/main.yml
    - include: agora-core-view/main.yml
