---
- name: High Availability & Load Balancing, configure agora-elections, authapi, sentry db
  sudo: true
  sudo_user: agoraelections
  lineinfile:
    dest="{{item.path}}"
    line="{{item.line}}"
    regexp="{{item.rx}}"
    state=present
  with_items:
    - line: "db.default.url=\\\"jdbc:postgresql://{{ load_balancing.slave.master_hostname if not config.load_balancing.is_master else 'localhost' }}:5432/agora_elections\\\""
      rx: "db.default.url[ \t]*="
      path: /home/agoraelections/agora-elections/conf/application.local.conf

    - line: "memcached.host=\\\"{{ load_balancing.slave.master_hostname if not config.load_balancing.is_master else '127.0.0.1' }}:11211\\\""
      rx: "memcached.host[ \t]*="
      path: /home/agoraelections/agora-elections/conf/application.local.conf

    - line: "        'HOST': '{{ load_balancing.slave.master_hostname if not config.load_balancing.is_master else '127.0.0.1' }}',"
      rx: "        'HOST': '"
      path: /home/authapi/authapi/authapi/auhapi/deploy.py

    - line: "        'HOST': '{{ load_balancing.slave.master_hostname if not config.load_balancing.is_master else '127.0.0.1' }}',"
      rx: "        'HOST': '"
      path: /home/sentry/sentry.conf.py


- name: High Availability & Load Balancing, restarting agora-elections
  sudo: true
  supervisorctl: name=agora-elections state=restarted
  with_items:
    - authapi
    - authapi_celery
    - sentry
    - sentry_celery
    - agora-elections

