---
- name: AgoraGui, copy logo image
  when: config.agora_gui.organization.logo_path != ''
  copy:
    "src={{config.agora_gui.organization.logo_path}}
    dest=/home/agoragui/agora-gui-admin/img/agora_voting_logo_white_100.png
    owner=agoragui
    group=agoragui
    mode=u=rw,g=r,o=r"

- name: AgoraGui, config beautify options
  sudo: true
  sudo_user: agoragui
  replace:
    "dest=/home/agoragui/{{item}}/Gruntfile.js
    regexp='beautify:.*'
    replace='beautify: {% if config.agora_gui.debug == 'true' %}true{% else %}false{% endif %}'"
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth

- name: AgoraGui, config compress options
  sudo: true
  sudo_user: agoragui
  replace:
    "dest=/home/agoragui/{{item}}/Gruntfile.js
    regexp='compress:.*'
    replace='compress: {% if config.agora_gui.debug == 'false' %}true{% else %}{}{% endif %},'"
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth
