---
- name: AgoraGui, copy logo image
  when: config.agora_gui.organization.logo_path != ''
  sudo: true
  copy:
    "src={{config.agora_gui.organization.logo_path}}
    dest=/home/agoragui/agora-gui-admin/img/agora_voting_logo_white_100.png
    owner=agoragui
    group=agoragui
    mode=u=rw,g=r,o=r"

- name: AgoraGui, config beautify options
  sudo: true
  sudo_user: agoragui
  replace:
    "dest=/home/agoragui/{{item}}/Gruntfile.js
    regexp='beautify:.*'
    replace='beautify: {% if config.agora_gui.debug == 'true' %}true{% else %}false{% endif %}'"
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth

- name: AgoraGui, config compress options
  sudo: true
  sudo_user: agoragui
  replace:
    "dest=/home/agoragui/{{item}}/Gruntfile.js
    regexp='compress:.*'
    replace='compress: {% if config.agora_gui.debug == 'false' %}true{% else %}{}{% endif %},'"
  with_items:
    - agora-gui-admin
    - agora-gui-elections
    - agora-gui-booth

- name: AgoraGui, copy static_extra_path
  when: config.agora_gui.static_extra_path != ''
  sudo: true
  copy:
    "src={{config.agora_gui.static_extra_path}}
    dest=/home/agoragui/static_extra/
    owner=agoragui
    group=agoragui"

- name: AgoraGui, config election limits
  sudo: true
  sudo_user: agoragui
  replace:
    "dest=/home/agoragui/agora-gui-admin/avAdmin/election-limits-service.js
    regexp='{{ item.key }}:.*'
    replace='{{ item.key }}: {{ item.value }},'"
  with_items:
    - { key: maxNumQuestions, value: "{{ config.election_limits.max_num_questions }}" }
    - { key: maxNumAnswers, value: "{{ config.election_limits.max_num_answers }}" }
    - { key: maxShortStringLength, value: "{{ config.election_limits.max_short_string_length }}" }
    - { key: maxLongStringLength, value: "{{ config.election_limits.max_long_string_length }}" }
