---
# this is needed to get the database tables created
- name: AgoraElections, creating tables
  sudo: true
  sudo_user: agoraelections
  shell: nohup ../activator-1.2.12-minimal/activator run > /dev/null 2>&1 & echo $! > run.pid ; sleep 60; wget http://localhost:9000/elections/api/election/1/ 2>/dev/null ; sleep 30; kill -9 $(cat run.pid)
         chdir=/home/agoraelections/agora-elections

- name: AgoraElections, activator clean & stage
  sudo: true
  sudo_user: agoraelections
  shell: /home/agoraelections/activator-1.2.12-minimal/activator clean; /home/agoraelections/activator-1.2.12-minimal/activator stage
         chdir=/home/agoraelections/agora-elections
